// HSE Learning Summit – UK | 7–8 July 2026 | Hilton Birmingham Metropole
// 51 named delegates included.
// Excluded: RWE (6 unnamed seats), Sonoco (8 unnamed seats) — add when names confirmed.
// Excluded: Principal People guests (George Wilson, Kim O'Brien, Tom Minshell, Dominic Barnard)
//   — recruitment firm attending as guests, not HSE decision makers to reference as connections.

module.exports = [
  { name: "Mesut Bicakci",          title: "Group Occupational Safety Chief",               company: "Limak Cement",                           industry: "Construction & Manufacturing" },
  { name: "Erhan Yilmazlar",        title: "Group Occupational Safety Chief",               company: "Limak Cement",                           industry: "Construction & Manufacturing" },
  { name: "Peter Jenkins",          title: "Lead Facilitator",                               company: "Simple Foundry",                         industry: "Safety Consulting" },
  { name: "Gareth Evans",           title: "Operational Resilience Director",                company: "BGO",                                    industry: "Real Estate & Investment" },
  { name: "Liam Simpson",           title: "Group Director of HSE",                         company: "Premier Technical Services Group",        industry: "Facilities Management" },
  { name: "Oliver Sanandres",       title: "Health & Safety Director",                      company: "City of London Corporation",             industry: "Public Sector" },
  { name: "Zoe Hayes",              title: "Head of SSR",                                   company: "BBC",                                    industry: "Media & Entertainment" },
  { name: "Ruth Denyer",            title: "Director of Production Safety",                 company: "Netflix",                                industry: "Media & Entertainment" },
  { name: "James Pomeroy",          title: "Director Global Health & Safety",               company: "Arup",                                   industry: "Engineering & Consulting" },
  { name: "Crystal Danbury",        title: "Director of Safety, Insurance & Occupational Wellbeing", company: "Sainsbury's",                  industry: "Retail" },
  { name: "Steff Williams",         title: "Director Safety Europe & APAC",                 company: "Sonoco",                                 industry: "Packaging & Manufacturing" },
  { name: "Helen Davitt",           title: "Health and Safety Director EMEA Operations",    company: "Digital Realty",                         industry: "Data Centres & Technology" },
  { name: "Francis Rawson",         title: "Group Director of Safety and Compliance",       company: "Places for People",                      industry: "Housing & Social Care" },
  { name: "Stuart Hughes",          title: "HSE Director",                                  company: "Mercedes-AMG F1",                        industry: "Motorsport & Manufacturing" },
  { name: "Marie-Louise Chandler",  title: "UK Safety Director",                            company: "QinetiQ",                                industry: "Defence & Aerospace" },
  { name: "Sarah Brummitt",         title: "Executive Coach & Leadership Expert",           company: "Sarah Brummitt Ltd",                     industry: "Coaching & Consulting" },
  { name: "Maeve O'Loughlin",       title: "HSE Transformation & Culture Consultant",       company: "Independent",                            industry: "Safety Consulting" },
  { name: "Emma Johnson",           title: "Director",                                      company: "PEAK4",                                  industry: "Safety Consulting" },
  { name: "David Laughlin",         title: "Head of Operational Safety",                    company: "Sainsbury's",                            industry: "Retail" },
  { name: "Lee Bird",               title: "Head of Safety",                                company: "Sainsbury's",                            industry: "Retail" },
  { name: "Emma Smith",             title: "Director of Commercial Development",            company: "Assurity Consulting",                    industry: "Safety Consulting" },
  { name: "Jamie Brooker",          title: "Consultancy Services Manager",                  company: "Assurity Consulting",                    industry: "Safety Consulting" },
  { name: "Mireille Stocker",       title: "Director of Learning & Development",            company: "Assurity Consulting",                    industry: "Safety Consulting" },
  { name: "Sue Parker-Tantush",     title: "Director",                                      company: "SPT Consulting",                         industry: "Safety Consulting" },
  { name: "David Renshaw",          title: "Head of Health & Safety",                       company: "City of London Corporation",             industry: "Public Sector" },
  { name: "Samantha Holmes",        title: "Group Head H&S",                                company: "Kingfisher PLC",                         industry: "Retail" },
  { name: "Gemma Wheeler",          title: "VP HSE Electronics Cyber & Automation UK",      company: "Leonardo",                               industry: "Defence & Aerospace" },
  { name: "Jamie McCleave",         title: "Head of Risk & Insurance",                      company: "Sainsbury's",                            industry: "Retail" },
  { name: "Chloe Kirkbride",        title: "Head of Health, Safety & Business Licencing",   company: "Sainsbury's",                            industry: "Retail" },
  { name: "Ellen Clancy",           title: "Health and Safety Manager",                     company: "DP World Southampton",                   industry: "Logistics & Ports" },
  { name: "Fawaz Bitar",            title: "SVP HSE & Carbon",                              company: "BP",                                     industry: "Energy & Oil & Gas" },
  { name: "Chris Stoves",           title: "Group Health and Safety Director",              company: "NEC Group",                              industry: "Events & Entertainment" },
  { name: "Susanne Lynas",          title: "Health and Safety Specialist",                  company: "BBC",                                    industry: "Media & Entertainment" },
  { name: "Brendan Harte",          title: "Regional HSE Director",                         company: "Hitachi Rail",                           industry: "Rail & Transport" },
  { name: "Sam Scholey",            title: "Environment Manager",                           company: "Hitachi Rail",                           industry: "Rail & Transport" },
  { name: "Keith Evans",            title: "Director of Colleague and Customer Safety",     company: "Places for People",                      industry: "Housing & Social Care" },
  { name: "Andrew Coward",          title: "Director of Property Compliance",               company: "Places for People",                      industry: "Housing & Social Care" },
  { name: "Philippa Miles",         title: "Production H&S Manager",                        company: "Netflix",                                industry: "Media & Entertainment" },
  { name: "Mark Cardwell",          title: "Head of HSE",                                   company: "Hotel Chocolat",                         industry: "Retail & Food Manufacturing" },
  { name: "Grainne Hill",           title: "HSE Manager Retail and Support Functions",      company: "Hotel Chocolat",                         industry: "Retail & Food Manufacturing" },
  { name: "Richard Hulland",        title: "Chief Risk & Assurance Officer",                company: "Veolia",                                 industry: "Environment & Utilities" },
  { name: "Robin Stowell",          title: "Safety Trainer",                                company: "ConverSafe",                             industry: "Safety Consulting" },
  { name: "Amy Matthews",           title: "Coordinator Production Safety",                 company: "Netflix",                                industry: "Media & Entertainment" },
  { name: "Tim Ingram",             title: "Managing Director",                             company: "Strategic Safety Consultants",           industry: "Safety Consulting" },
  { name: "Lisa Cobb",              title: "Global Head of Safety",                         company: "SSP Group",                              industry: "Food & Beverage" },
  { name: "Chris Lea",              title: "SVP Global Head EHS",                           company: "Evotec",                                 industry: "Life Sciences & Pharma" },
  { name: "Rebecca Wood",           title: "Head of HSE & Wellbeing",                       company: "UCB",                                    industry: "Pharmaceuticals" },
  { name: "Paul Griffin",           title: "Director",                                      company: "631 Risk",                               industry: "Risk Consulting" },
  { name: "Rachel Gidman",          title: "Executive Director of People & Culture",        company: "Cardiff and Vale University Health Board", industry: "Healthcare" },
  { name: "Robert Warren",          title: "Assistant Director of Health, Safety & Fire",   company: "Cardiff and Vale University Health Board", industry: "Healthcare" },
  { name: "Ian Leslie",             title: "Author",                                        company: "Curious",                                industry: "Publishing & Behavioural Science" },
];
